
- title: Conference Chairing
  type: time_table
  contents:
    - title: General Co-Chair
      year: 2024
      description:
       - "Cyber-Physical Systems and Internet-of-Things Week (CPS-IoT-Week)"

    - title: Director
      year: 2023
      description:
       - "Croucher Advanced Study Institutes (Croucher ASI), AI for Internet of Things"
